export const state = () => ({
    allItems: {
        poo: {
          title: "POO",
          items: [
            { icon: "mdi-play", 
              title: "POO", 
              to: "/poo/intro" 
            },
            {
              icon: "mdi-text-box-outline",
              title: "Abstracción",
              to: "/poo/abstraccion",
            },
            { icon: "mdi-text-box-outline", 
              title: "Clases", 
              to: "/poo/clases" },
            {
              icon: "mdi-text-box-outline",
              title: "Sobrecarga | ejercicio",
              to: "/poo/sobrecarga",
            },
            {
              icon: "mdi-text-box-outline",
              title: "Comp. y Agreg. | ejercicio",
              to: "/poo/agregacionycomposicion",
            },
            {
              icon: "mdi-text-box-outline",
              title: "Herencia",
              to: "/poo/herencia",
            },
            { icon: "mdi-play",
              title: "Persistencia", 
              to: "/poo/persistencia" },
          ],
        },
        android: {
          title: "Android",
          items: [
            { icon: "mdi-play", title: "Instalación", to: "/android/and01" },
            { icon: "", title: "Sumadora App", to: "/android/and02" },
            { icon: "", title: "Activities y bundles", to: "/android/and03" },
            { icon: "", title: "Persistencia", to: "/android/and04" },
          ],
        },
        estructuraDeDatos: {
          title: "Estructura de Datos",
          items: [
            { icon: "mdi-text-box-outline", title: "Introduccion", to: "/eDatos/01" },
            { icon: "mdi-text-box-outline", title: "Pilas", to: "/eDatos/02" },
            { icon: "mdi-code-tags", title: "Pilas <code>", to: "/eDatos/03" },
            { icon: "mdi-text-box-outline", title: "Colas", to: "/eDatos/04" },
            { icon: "mdi-code-tags", title: "Colas <code>", to: "/eDatos/05" },
            { icon: "mdi-text-box-outline", title: "Listas", to: "/eDatos/06" },
            { icon: "mdi-code-tags", title: "Listas simples normal", to: "/eDatos/07" },
            {
              icon: "mdi-code-tags",
              title: "Listas simples circular",
              to: "/eDatos/08",
            },
            { icon: "mdi-code-tags", title: "Listas Dobles normal", to: "/eDatos/09" },
            {
              icon: "mdi-code-tags",
              title: "Listas Dobles circular",
              to: "/eDatos/10",
            },
            { icon: "mdi-text-box-outline", title: "Recursividad", to: "/eDatos/11" },
            { icon: "mdi-text-box-outline", title: "Arboles", to: "/eDatos/12" },
            { icon: "mdi-code-tags", title: "Arboles <code>", to: "/eDatos/13" },
          ],
        },
        programacionEstructurada: {
          title: "Programacion Estructurada",
          items: [
            {icon:'', title: 'Introducción', to:'/pEstructurada/01'},
            {icon:'', title: '¿Que es un algoritmo? | Algoritmos y caracteristicas', to:'/pEstructurada/02'},
            {icon:'', title: 'Variables, constantes y tipos de Datos', to:'/pEstructurada/03'},
            {icon:'', title: 'Datos de Entrada y Salida', to:'/pEstructurada/04'},
            {icon:'', title: 'Operaciones aritmeticos (+, -, *, /,  %)', to:'/pEstructurada/05'},
            {icon:'', title: 'Etapas de resolucion de problemas', to:'/pEstructurada/06'},
            {icon:'', title: 'Estructura If', to:'/pEstructurada'},
            {icon:'', title: 'Operadores relacionales (mayor, menor igual, distinto)', to:'/pEstructurada'},
            {icon:'', title: 'Operadores lógicos (&&, ||, !)', to:'/pEstructurada'},
            {icon:'', title: 'Ejercicios con IF', to:'/pEstructurada'},
            {icon:'', title: 'Estructura Switch', to:'/pEstructurada'},
            {icon:'', title: 'Ejercicios con Switch', to:'/pEstructurada'},
            {icon:'', title: 'Sentencia While', to:'/pEstructurada'},
            {icon:'', title: 'Ejercicios con While', to:'/pEstructurada'},
            {icon:'', title: 'Sentencia For', to:'/pEstructurada'},
            {icon:'', title: 'Ejercicios con For', to:'/pEstructurada'},
            {icon:'', title: 'Funciones y Procedimientos', to:'/pEstructurada'},
            {icon:'', title: 'Strings', to:'/pEstructurada'},
            {icon:'', title: 'Arreglos', to:'/pEstructurada'},
          ],
        },
        poo2: {
          title: "POO",
          items: [
            {icon: 'mdi-text-box-outline', title: 'Introduccion', to:'/poo2/01', block:false},
            {icon: 'mdi-text-box-outline', title: 'Que es POO', to:'/poo2/02', block:false},
            {icon: 'mdi-text-box-outline', title: 'Que es un OBJETO?', to:'/poo2/03', block:false},
            {icon: 'mdi-text-box-outline', title: 'ABSTRACCIÓN y Clases', to:'/poo2/04', block:false},
            {icon: 'mdi-text-box-outlin', title: 'Clases', to:'/poo2/05', block:false},
            {icon: 'mdi-lock', title: 'Diagramas de clase UML', to:'/poo2/', block:true},
            {icon: 'mdi-lock', title: 'Implementación de nuestras clases en código', to:'/poo2/', block:true},
            {icon: 'mdi-lock', title: 'Constructores y Destructores', to:'/poo2/', block:true},
            {icon: 'mdi-lock', title: 'ENCAPSULACION, Getters y Setters', to:'/poo2/', block:true},
            {icon: 'mdi-lock', title: 'Sobrecarga de Métodos', to:'/poo2/', block:true},
            {icon: 'mdi-lock', title: 'Sobrecarga de Operadores', to:'/poo2/', block:true},
            {icon: 'mdi-lock', title: 'Herencia simple', to:'/poo2/', block:true},
            {icon: 'mdi-lock', title: 'Herencia multiple', to:'/poo2/', block:true},
            {icon: 'mdi-lock', title: 'Agregación', to:'/poo2/', block:true},
            {icon: 'mdi-lock', title: 'Composición', to:'/poo2/', block:true},
            {icon: 'mdi-lock', title: 'Excepciones', to:'/poo2/', block:true},
            {icon: 'mdi-lock', title: 'Persistencia de Objetos', to:'/poo2/', block:true},
          ],
        },
        home: { title: "Sobre la página", items: [{icon:"mdi-information-outline", title:"Información", to:"/nosotros"}] },
      },
  })